### PR TITLE
Build v2.0.2

### PR DESCRIPTION
**Pull request by xylar**
This is the version expected in the current release of Moab

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Merging to a branch `2.0.2` so I don't have to put master back afterward.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
This should be able to be built once `netcdf-cxx-legacy-feedstock` is up and running...

**Comment by xylar** [comment]
@jhkennedy, I need this older version of TempestRemap for building moab.  Do you want to review this or can I just merge once CI has passed.  Note, this will go to a `2.0.2` branch, not to `master` so won't affect future updates to `master`.

**Comment by xylar** [comment]
I'm going to merge.  We can address concerns (if any) later on.

**Comment by jhkennedy** [comment]
@xylar This looks good to me. I see a few more `--with` statements in the `build.sh`, should those be added to the current version? I *think* it was picking up all those in the current build, but I'm not 100% sure

**Comment by xylar** [comment]
@jhkennedy, I don't think they are necessary. I put them in when I was debugging and decided to leave them.

**Pull request merged**
