### PR TITLE
DO NOT MERGE: test build of current master

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
This PR is for trying out the current `master` branch in anticipation of a pending release concurrent with the next version of MOAB.

**Comment by xylar** [comment]
Woo, hoo!  We should be good once a new release happens.  I'll leave this open so we can test again right before release.

**Comment by jhkennedy** [comment]
:tada: :tada: :tada:

**Comment by xylar** [comment]
@conda-forge-admin, please restart CI

**Comment by xylar** [comment]
Great, just wanted to check that thing are still working after a month.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
