### PR TITLE
Rebuild 2.0.2 with latest pinnings

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I can't figure out the linux OpenMPI build failure.  Will try to debug over the weekend.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by jhkennedy** [comment]
hmm, interesting, in the build log we're getting: 

```
/home/conda/feedstock_root/build_artifacts/tempest-remap_1579803245288/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libmpi_cxx.so.40, needed by /home/conda/feedstock_root/build_artifacts/tempest-remap_1579803245288/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libnetcdf_c++.so, not found (try using -rpath or -rpath-link)
```

I though adding the `run_exports` might fix it, but it appears not

**Comment by xylar** [comment]
It must have to do with `netcdf-cxx-legacy` or one of the other differences between this version and 2.0.3, because that one is fine...

**Comment by jhkennedy** [comment]
Maybe it's this call:

https://github.com/conda-forge/tempest-remap-feedstock/blob/1bc103df1cc5e97adc2d4e1bca34ac9a44dd7b1e/recipe/build.sh#L21-L25

While in master, we've dropped some of those:

https://github.com/conda-forge/tempest-remap-feedstock/blob/a18f5c234f5e9376150e61c2287ba015b19ce013/recipe/build.sh#L21-L24

**Comment by jhkennedy** [comment]
Hmm, or, (I really don't think this should matter) it's that `{{mpi}} is the first host and run requirement for v2.0.3 but last for v2.0.2

**Comment by xylar** [comment]
@jhkennedy, I think a rebuild of `netcdf-cxx-legacy` will take care of it, and the problem isn't here.  It worked on my laptop.  Please hard reset back one commit since I think we need the `--with`s and I'll work on a PR on `netcdf-cxx-legacy`.

**Comment by xylar** [comment]
https://github.com/conda-forge/netcdf-cxx-legacy-feedstock/pull/3

**Comment by jhkennedy** [comment]
Gotcha. If a rebuild of `netcdf-cxx-legacy` doesn't do it, we might need to add something like what HDF5 did to the recipe:

https://github.com/conda-forge/hdf5-feedstock/blob/786d09b4ad72377e6ca4d1f2279d88733caf8606/recipe/meta.yaml#L24-L32

**Comment by xylar** [comment]
I believe this bit:
https://github.com/xylar/tempest-remap-feedstock/blob/2.0.2_update_libnetcdf/recipe/meta.yaml#L37-L40
is equivalent to what you're seeing in hdf5 because we don't have any extra outputs like they do.  I don't fully understand when the `if mpi...` is needed and when not but let's see.

That is what I added to `netcdf-cxx-legacy` and either that or just the fact that I did a new build fixed `tempest-remap` 2.0.2 in a local build.  Fingers crossed...

**Comment by xylar** [comment]
@conda-forge-admin, please rerun ci

**Comment by xylar** [comment]
Okay, clearly these `run_exports` are vital and I missed them in at least a few places.  I'll possibly have a number of other feedstocks to clean up down the road...

**Comment by xylar** [comment]
Thanks for your help, @jhkennedy.  I wouldn't have figured this one out without you.

**Comment by jhkennedy** [comment]
Glad to help @xylar! I'm still a little confused by v2.0.3 worked with the prev. build of `netcdf-cxx-legacy` but not v2.0.2, but I'm glad the rebuild worked!

**Comment by xylar** [comment]
v2.0.3 eliminated the dependency on `netcdf-cxx-legacy`.  Given that that was the main difference, I suspected that might be why this build was failing and that wasn't.

**Comment by jhkennedy** [comment]
:man_facepalming: right -- don't know how I missed that!

**Comment by jhkennedy** [comment]
Wait, should it not be in the recipe then?

https://github.com/conda-forge/tempest-remap-feedstock/blob/master/recipe/meta.yaml#L67

**Comment by xylar** [comment]
Okay, weird.  No, I don't think it should be in the recipe.

**Comment by xylar** [comment]
It seems to have been added by mistake as part of the MPI build matrix.  I'll fix it now.  Oops!

**Comment by jhkennedy** [comment]
That explains why I was so confused! :smile:

**Pull request merged**
